### ISSUE TITLE
How to set SENDER ID?

### ISSUE THREAD

**Issue by saraswat19** [craftsys/msg91-laravel-notification-channel#1]
After the recent regulation of TRAI in India, Sender ID is required to send messages. How can we set it in this package?

**Comment by sudkumar** [comment]
Within you `config/services.php`, under `msg91` key, you can specify this configuration.

```php
<?php

return [
  // ...
  // along with other services
  'msg91' => [
    'key' => "<YOUR_MSG91_AUTH_KEY>",
    'from' => "<YOUR_SENDER_ID_HERE>"
  ]
```

If you want to customize the sender ID when notifying, you can call the `message->from` method on the OTP or SMS Messages.

```php
// .. an example notification that has `msg91` in channels list
class LoginOTPVerificationNotification {
  // add msg91 in the channels list
  public function via ()
  {
    return ['msg91'];
  }

 // craft your notification for msg91
  public function toMsg91($notifiable)
  {
    return (new \Craftsys\Notifications\Messages\Msg91OTP);
        ->from("YOUR_SENDER_ID_HERE");
  }

}
```

> Pro Tip: This Messages\Msg91OTP or Messages\Msg91SMS extends [Craftsys\Msg91\Options](https://github.com/craftsys/msg91-php/blob/master/src/Options.php) so you can provide all available configuration when crafting your notification for msg91 channel.

---

A list of available options can be found here  https://github.com/craftsys/msg91-php#configuration.

Please let me know if it is helpful.

**Comment by saraswat19** [comment]
Okay I will try this.

Thanks

**Comment by sudkumar** [comment]
@saraswat19 Did it resolve your issue ?

**Comment by sudkumar** [comment]
Sounds like it is fixed. Closing now.

If not, please feel free to comment here.
