### ISSUE TITLE
Call to undefined method Craftsys\Msg91\Facade\Msg91::send()

### ISSUE THREAD

**Issue by dhruva81** [craftsys/msg91-laravel-notification-channel#3]
Hi
I am trying to send sms but I am getting following error.
```
Error
Call to undefined method Craftsys\Msg91\Facade\Msg91::send() 
```

I am using following codes in my notification channel
```
public function via ($notifiable) {
    return ['msg91'];
}

public function toMsg91($notifiable)
{
    return (new \Craftsys\Notifications\Messages\Msg91SMS)
        ->content("Message is this");
}
```

Please let me know, is there any additional  setting required.

**Comment by sudkumar** [comment]
Hi @dhruva81  Thanks for reporting.

Looks like this error is coming from somewhere else. The facade is not been used while sending the notification so this error can not come while sending the `sms via notification`.

Are you sending SMS from somewhere else in your application (other than this notification class)? i.e. directly calling `Msg91::send()`

**Comment by dhruva81** [comment]
Hi @sudkumar 
Thank you for replying

I have checked carefully again and I am not using Msg91::send() anywhere else on platform. 

Also, When I am trying to send otp using following codes, otps are sending but sms are not sending.

```
Msg91::otp()
  ->to(919xxxxxxxxx) 
  ->send(); 

Msg91::sms()
    ->to(919xxxxxxxxx) 
    ->message("Hi This is test message. Hopefully you have received it.") 
    ->send();
```

I am testing this on Laravel v8 and error is still showing

```
Error
Call to undefined method Craftsys\Msg91\Facade\Msg91::send() 
```

**Comment by sudkumar** [comment]
Alright. Thanks for more information. I will check it again.

**Comment by sudkumar** [comment]
@dhruva81  Just tested that Msg91 API endpoints have been updated for sending SMS and older apis has been removed from the documentation. 😢  They have introduced a new thing :`Flows` to send SMS now.

I need to read the new docs and update the API accordingly.

**Comment by dhruva81** [comment]
Thank you for giving your time... 
I am waiting for upgraded version of this package. 
Thanks 😊

**Comment by sudkumar** [comment]
I have updated the [base package](https://github.com/craftsys/msg91-php) to handle the new send sms api. I need your help in testing the SMS api of which I don't have subscription.

To Test the new apis:

- Uninstall the `craftsys/msg91-laravel-notification-channel`
- Install **msg91-php** `composer require craftsys/msg91-php:0.10.1`
- open artisan with `php artisan`
- run the following code to test if send sms is working

```php
$config = ['key' => "<your_auth_key>"];
$client = new \Craftsys\Msg91\Client($config);
$client->sms()->to(<your_phone_number_with_courty_code_without_any_signs>)->flow("<flow_id_here>")->send();
```

Please let me know of results.

**Comment by dhruva81** [comment]
I have tried steps provided by you and I am getting following exception

```
Craftsys\Msg91\Exceptions\ResponseErrorException
Receiver Is Missing 
```

**Comment by sudkumar** [comment]
Thank you. I was getting the same error when testing locally. I could not find any documents regarding this issue. I will look more into it. Thanks again.

**Comment by dhruva81** [comment]
When I am trying using following codes on there documentation page .. sms are going

```
    $senderId = "<sender_id>";
    $flow_id = '<flow_id>';
    $recipients = array(
        array(
            "mobiles" => "<mobile>",
            "VAR1" => "VALUE 1",
            "VAR2" => "VALUE 2"
        ),
        array(
            "mobiles" => "<mobile>",
            "VAR1" => "VALUE 1",
            "VAR2" => "VALUE 2"
        )
    );

    //Prepare you post parameters
    $postData = array(
        "sender" => $senderId,
        "flow_id" => $flow_id,
        "recipients" => $recipients,
    );
    $postDataJson = json_encode($postData);

    $url="https://control.msg91.com/api/v5/flow/";

    $curl = curl_init();
    curl_setopt_array($curl, array(
        CURLOPT_URL => "$url",
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_CUSTOMREQUEST => "POST",
        CURLOPT_POSTFIELDS => $postDataJson,
        CURLOPT_HTTPHEADER => array(
            "authkey: <auth_key>",
            "content-type: application/json"
        ),
    ));
    $response = curl_exec($curl);
    $err = curl_error($curl);
    curl_close($curl);
    if ($err) {
        echo "cURL Error #:" . $err;
    } else {
        echo $response;
    }
```

**Comment by sudkumar** [comment]
So the api end point is "https://control....". I have it "https://api...".

Where did you find it out?

**Comment by dhruva81** [comment]
https://docs.msg91.com/collection/msg91-api-integration/5/send-sms-via-flow/T29N6CRT

**Comment by sudkumar** [comment]
There the url is https://api.msg91.com/api/v5/flow/. But you mentioned it to be control instead of api! 

And BTW, they have same endpoint for creating a flow and sending SMS!! 🙄

Can you please tell me where did you get that code sample. Is it from there official site or somewhere else?

**Comment by dhruva81** [comment]
I am not able to recall properly whether I changed the url just for experimenting.. 
but I guess I have not made any change in the code .. only added my mobile number as recipients, sender id , flow id and added name key in $postData array.

One issue I am facing .. in flow I have to created templates.
I created a variable in template and passing through $postData array  like below

```
  //Prepare you post parameters
    $postData = array(
        "sender" => $senderId,
        "flow_id" => $flow_id,
        "recipients" => $recipients,
        "name" => '<name_here'>,
    );
```
But these custom variables are not passing in the flow template and I am receiving null values at variable place in sms :(

**Comment by sudkumar** [comment]
What does this "name" stand for? Is this your custom variable in the template?

**Comment by dhruva81** [comment]
'name' is custom variable in sms template. 

Sample SMS template example - 

Dear ##name##
Thank you, we have received your application . 

I don't know, whether this is correct way of passing values to sms template.. I was just experimenting and it was not working :(

**Comment by sudkumar** [comment]
Oh.. the custom variables needs to passed in the recipients fields along with the mobile numbers.

```json
"recipients": [
  { "mobiles": "919999999999", "name": "your name here"}
]
```

The Msg91 api end point issue have been fixed in their docs. I am updating the package.

**Comment by sudkumar** [comment]
I have updated the [base package](https://github.com/craftsys/msg91-php).

Please update to the latest version and let me know how it goes.

```
composer require craftsys/msg91-php:0.11.0
```

Also the docs have been updated to explain the template variables and receiver keys.


Step to test are same as earlier. Just open the php artisan and run following code.

```php
$config = ['key' => "<your_auth_key>"];
$client = new \Craftsys\Msg91\Client($config);
$client->sms()->to(<your_phone_number_with_courty_code_without_any_signs>)->flow("<flow_id_here>")->send();
```

**Comment by dhruva81** [comment]
Hi.. I have tested with your new version '0.11.0'

Unfortunately I am receiving same error :(
```
Craftsys\Msg91\Exceptions\ResponseErrorException
Receiver Is Missing 
```

OTPs are going but SMS are not going

```
    $config = ['key' => "key_here"];

    $client = new \Craftsys\Msg91\Client($config);
    
    $client->otp()
    ->to(91999999999) // phone number with country code
    ->send();

    $client->sms()
        ->to(91999999999)
        ->flow("flow_id")
        ->message("New Message from flow")
        ->send();
```

**Comment by sudkumar** [comment]
Sorry my friend. My Bad.. I accidentally reverted the URL for send SMS. Updated and release a new version.

Please test the latest release:

```
composer require craftsys/msg91-php:0.11.1
```

**Comment by dhruva81** [comment]
Thank you.
Now error is not coming :)
But Msgs are not delivering.
Please also let me  khowm how do I pass variables in flow sms template.
Also, will laravel notifications package work with this?

**Comment by sudkumar** [comment]
Thanks for help.

For variable, [docs here](https://github.com/craftsys/msg91-php#flow-variables)

> Please also let me know how do I pass variables in flow sms template.

You can pass the recipients array with your variable names inside each element. For example, assuming that you have `##name##` in your template. Then we will create recipients array as follows:

```php
$recipients = [
  [
    'mobiles' => '9199999999',
    // here, "name" is the variable and "User Name" is the value for it
    'name' => 'User Name'
  ]
]

// now send the sms to recipients
$client->sms()->flow("123123")->recipients($recipients)->send();
```

> But Msgs are not delivering.

I don't have subscription to SMS service from Msg91. I will look into it. Are there no other errors coming when sending sms ?


> Also, will Laravel notifications package work with this?

I will update Laravel binding once this issue is resolved in the base package.

**Comment by dhruva81** [comment]
Thank you for guiding.
There is no error coming. But sms are not delivering :(
I can share my account credentials for your testing purpose. Please let me know.

**Comment by sudkumar** [comment]
That would really help. Please create a new token and flow. You can share them at `luckysud4 [at] gmail [dot] com`

> no spaces in email address

**Comment by dhruva81** [comment]
Please check your inbox.

**Comment by sudkumar** [comment]
Alright.

**Comment by sudkumar** [comment]
> When I am trying using following codes on there documentation page .. sms are going
> 
> ```
>     $senderId = "<sender_id>";
>     $flow_id = '<flow_id>';
>     $recipients = array(
>         array(
>             "mobiles" => "<mobile>",
>             "VAR1" => "VALUE 1",
>             "VAR2" => "VALUE 2"
>         ),
>         array(
>             "mobiles" => "<mobile>",
>             "VAR1" => "VALUE 1",
>             "VAR2" => "VALUE 2"
>         )
>     );
> 
>     //Prepare you post parameters
>     $postData = array(
>         "sender" => $senderId,
>         "flow_id" => $flow_id,
>         "recipients" => $recipients,
>     );
>     $postDataJson = json_encode($postData);
> 
>     $url="https://control.msg91.com/api/v5/flow/";
> 
>     $curl = curl_init();
>     curl_setopt_array($curl, array(
>         CURLOPT_URL => "$url",
>         CURLOPT_RETURNTRANSFER => true,
>         CURLOPT_CUSTOMREQUEST => "POST",
>         CURLOPT_POSTFIELDS => $postDataJson,
>         CURLOPT_HTTPHEADER => array(
>             "authkey: <auth_key>",
>             "content-type: application/json"
>         ),
>     ));
>     $response = curl_exec($curl);
>     $err = curl_error($curl);
>     curl_close($curl);
>     if ($err) {
>         echo "cURL Error #:" . $err;
>     } else {
>         echo $response;
>     }
> ```

Earlier you mentioned this was working. Can you try it again with some modifications


```php
$url="https://api.msg91.com/api/v5/flow/";
//Prepare you post parameters
$postData = array(
    "flow_id" => "<your_flow_id>",
    "recipients" => [
      "mobiles" => "<your mobile number>"
    ],
);

try {
  $resp = (new \GuzzleHttp\Client())->post($url, [
    "form_params" => $postData,
    "headers" => [
       'authkey' => "<your_auth_key>"
    ]
  ]);
  var_dump($resp);
} catch (\Exception $e) {
  var_dump($e)
}

```

---
P.S. That's all this package does.

**Comment by dhruva81** [comment]
I have tried with your code. 
```
object(GuzzleHttp\Psr7\Response)#1804 (6) { ["reasonPhrase":"GuzzleHttp\Psr7\Response":private]=> string(2) "OK" ["statusCode":"GuzzleHttp\Psr7\Response":private]=> int(200) ["headers":"GuzzleHttp\Psr7\Response":private]=> array(9) { ["Date"]=> array(1) { [0]=> string(29) "Tue, 29 Sep 2020 09:15:47 GMT" } ["Content-Type"]=> array(1) { [0]=> string(24) "text/html; charset=UTF-8" } ["Transfer-Encoding"]=> array(1) { [0]=> string(7) "chunked" } ["Connection"]=> array(1) { [0]=> string(10) "keep-alive" } ["Server"]=> array(1) { [0]=> string(5) "nginx" } ["Set-Cookie"]=> array(1) { [0]=> string(109) "PHPSESSID=2v1kqdrv80t9jfkoi660k36sg1; expires=Fri, 09-Oct-2020 09:15:47 GMT; Max-Age=864000; path=/; HttpOnly" } ["Expires"]=> array(1) { [0]=> string(29) "Thu, 19 Nov 1981 08:52:00 GMT" } ["Cache-Control"]=> array(1) { [0]=> string(35) "no-store, no-cache, must-revalidate" } ["Pragma"]=> array(1) { [0]=> string(8) "no-cache" } } ["headerNames":"GuzzleHttp\Psr7\Response":private]=> array(9) { ["date"]=> string(4) "Date" ["content-type"]=> string(12) "Content-Type" ["transfer-encoding"]=> string(17) "Transfer-Encoding" ["connection"]=> string(10) "Connection" ["server"]=> string(6) "Server" ["set-cookie"]=> string(10) "Set-Cookie" ["expires"]=> string(7) "Expires" ["cache-control"]=> string(13) "Cache-Control" ["pragma"]=> string(6) "Pragma" } ["protocol":"GuzzleHttp\Psr7\Response":private]=> string(3) "1.1" ["stream":"GuzzleHttp\Psr7\Response":private]=> object(GuzzleHttp\Psr7\Stream)#1806 (7) { ["stream":"GuzzleHttp\Psr7\Stream":private]=> resource(709) of type (stream) ["size":"GuzzleHttp\Psr7\Stream":private]=> NULL ["seekable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["readable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["writable":"GuzzleHttp\Psr7\Stream":private]=> bool(true) ["uri":"GuzzleHttp\Psr7\Stream":private]=> string(10) "php://temp" ["customMetadata":"GuzzleHttp\Psr7\Stream":private]=> array(0) { } } } 
```
No SMS delivered :(

**Comment by sudkumar** [comment]
New version released 

```
composer require craftsys/msg91-php:0.11.2
```

🤞 I hope this will work. Please test and let me know.

**Comment by dhruva81** [comment]
Wow... The SMS are now delivering.
Thank you very much.

**Comment by sudkumar** [comment]
Thank you so much. I will update the docs and then I will update the Laravel binding.

I will let you know in comments once this package gets updated with latest dependencies.

**Comment by sudkumar** [comment]
@dhruva81 Please test the issue with the latest release.

> Please uninstall `craftsys/msg91-php` which you might have installed while testing.

```
composer require craftsys/msg91-laravel-notification-channel:^0.4.1
```

Feel free to reopen if the issue still exists.

**Comment by dhruva81** [comment]
@sudkumar Thank you sir.. 
I have updated to latest version 0.4.2
and It is now working perfectly.
Thanks a lot.
